### ISSUE TITLE
Which SDK should we use?

### ISSUE THREAD

**Issue by edolix** [OneSignal/onesignal-ruby-api#37]
### How can we help?

Hey there! 

I think there are other kind-of _related_ issues like: #31 #34 #30 #20 #12 

Looks like on rubygems there are two different SDKs: 

1. https://rubygems.org/gems/onesignal
2. https://rubygems.org/gems/onesignal_sdk

`onesignal_sdk` matches `OneSignal::VERSION` (2.0.2) but in the installation instructions you mentioned `onesignal` that is still on `1.0.1`.

https://github.com/OneSignal/onesignal-ruby-api/blob/6a970c476bfb41ab55d603354bec014bc6bfbbc0/lib/onesignal/version.rb#L13-L15

The repo is missing the git tag for 2.0.2 so there's a bit of confusion on which SDK should be used.

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by edolix** [comment]
Note: tried to run with `onesignal_sdk` and i got a `NameError: uninitialized constant OneSignal` from the initializer

**Comment by bmulholland** [comment]
Bundler will auto-require the lib, if there's a file with a name matching the name of the gem. In the case of `onesignal_sdk`, there's no matcing file; changing your Gemfile to hint Bundler with the name of the lib to require will remove the need to add the `require`. Specifically: `gem "onesignal_sdk", require: "onesignal"`

**Comment by edolix** [comment]
@bmulholland thanks for the hint! 

About the _other_ gem: i can confirm that solved #30 (and i guess it also solve all the others as well)

**Comment by bmulholland** [comment]
I was about to adopt `[onesignal_sdk](https://rubygems.org/gems/onesignal_sdk)` myself, but paused: it's not published by someone clearly attached to OneSignal on RubyGems. Neither is the original, for that matter. How do we know one or both of them is under control of OneSignal? Could one of them be a supply chain attack? There's substantial security concerns here :\

**Comment by edolix** [comment]
Maybe @rgomezp or @jkasten2 can help us here?

**Comment by jkasten2** [comment]
@bmulholland @edolix Thanks for reporting!

* `onesignal` - https://rubygems.org/gems/onesignal - Is the official OneSignal Ruby gem.
* `onesignal_sdk` - https://rubygems.org/gems/onesignal_sdk - Is unofficial and is not affiliated with OneSignal. We have reached out to Ruby Gems on this gem, so once resolved, others do not run into this confusion in the future.

`onesignal` gem 
* 1.0.1 - Currently the latest major release
* 2.x.x - This is a beta branch, with OneSignal's User Model API. However it isn't listed available on Ruby Gems, this is something we will investigate why it wasn't published publicly.

Depending on what APIs you need to integrate with you may want to use the OneSignal ruby gem `onesignal` or use the REST API directly. If you simply want to send notifications `onesignal` will work well for this. If you need to use [User Model APIs](https://documentation.onesignal.com/reference/create-user) you will want to use the REST API directly, as this isn't an official production ready gem for them yet.

**Comment by edolix** [comment]
Thanks @jkasten2!

> If you simply want to send notifications onesignal will work well for this.

That's true only if we don't have to use _some_ fields like #30 or #34

**Comment by sherwinski** [comment]
Closing this issue as the original question is answered. All other issues regarding gem releases and missing features will be tracked in their respective tickets.
